CREATE TABLE tasks (
    id SERIAL PRIMARY KEY NOT NULL,
    task VARCHAR(255) NOT NULL,
    priority INTEGER CHECK (priority >= 1 AND priority <= 5) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);